@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDM3ODAxNjJ9.18kAku9bPSBIe_qxU_ddlq9HCMkW53G_y-kDYr5bzqQ

###Create Actor
POST http://localhost:3000/actors
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "first_name": "",
  "last_name": "Totoo",
  "known_for": "Who knows what?",
  "gender": "male",
  "age": 22
}

###Update Actor
PATCH http://localhost:3000/actors/19
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "first_name": "John",
  "last_name": "Greenberg",
  "gender": "male",
  "age": 79
}

###Delete Actor
DELETE http://localhost:3000/actors/18
Authorization: Bearer {{ jwt }}

###Create Movie
POST http://localhost:3000/movies
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "title": "Thor",
  "plot": "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.",
  "director": "Kenneth Branagh",
  "english": true
}

###Update movie
PATCH http://localhost:3000/movies/7
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "english": false,
  "director": ""
  
}

###Delete movie
DELETE http://localhost:3000/movies/11
Authorization: Bearer {{ jwt }}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "brian",
  "email": "brian@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "kevin@gmail.com",
  "password": "password"
}

### 
POST http://localhost:3000/movie_genres
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "movie_id": 10,
  "genre_id": 3
}